### ISSUE TITLE
tlmgr install: package hyphen-korean not present in repository

### ISSUE THREAD

**Issue by letitbk** [bit2r/bitPublish#63]
안녕하세요! 패키지를 활용해서 `quarto preview --to bitPublish-pdf` 명령어를 실행시키면 다음과 같은 에러가 나오는데요, 제가 여러번 mactex를 지웠다가 설치하는걸 반복하다가, 다시 tinytex를 설치해보기도 하고 했는데, 같은 에러가 반복되어서..., 뭔가 저장소를 다르게 지정을 해야하는건가 싶기도 한데, 혹시 어떻게 하면 문제를 해결할 수 있을지 알 수 있을까여?

```
running xelatex - 1
  This is XeTeX, Version 3.141592653-2.6-0.999996 (TeX Live 2024) (preloaded format=xelatex)
   restricted \write18 enabled.
  entering extended mode
  
> 1 package to install
> installing hyphen-korean (1 of 1)
ERROR: tlmgr returned a non zero status code
tlmgr install: package hyphen-korean not present in repository.
tlmgr: action install returned an error; continuing.
tlmgr: An error has occurred. See above messages. Exiting.


Stack trace:
tlmgr install: package hyphen-korean not present in repository.
tlmgr: action install returned an error; continuing.
tlmgr: An error has occurred. See above messages. Exiting.

    at Object.onComplete (file:///Applications/quarto/bin/quarto.js:92737:64)
    at eventLoopTick (ext:core/01_core.js:153:7)
    at async renderFiles (file:///Applications/quarto/bin/quarto.js:77991:16)
    at async renderProject (file:///Applications/quarto/bin/quarto.js:78369:25)
    at async serveProject (file:///Applications/quarto/bin/quarto.js:100006:24)
    at async Command.actionHandler (file:///Applications/quarto/bin/quarto.js:100699:9)
    at async Command.execute (file:///Applications/quarto/bin/quarto.js:8015:13)
    at async Command.parseCommand (file:///Applications/quarto/bin/quarto.js:7905:20)
    at async quarto (file:///Applications/quarto/bin/quarto.js:118040:5)
    at async file:///Applications/quarto/bin/quarto.js:118052:9
```

**Comment by letitbk** [comment]
이와 관련해서, 다시 새로운 폴더에 bitpublish를 install하고 나서 다시 rendering하고 나니, 다음과 같은 문제가 발생하는데요, 혹시 아래의 문제를 어떻게 해결할 수 있을지 알 수 있을까요? 
```
Rendering PDF
running xelatex - 1
  This is XeTeX, Version 3.141592653-2.6-0.999996 (TeX Live 2024) (preloaded format=xelatex)
   restricted \write18 enabled.
  entering extended mode
  
updating tlmgr

updating existing packages
ERROR: 
compilation failed- error
Package ltcaption Error: \caption is not available in longtable* environment.

See the ltcaption package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.1585 ...Borgatti, Mehra and others 2009, p 894)}
                                                  \\ 
```

**Comment by rjmcmc** [comment]
bitPublish를 설치한 폴더에서 _quarto.yml 을 Rstudio에서 열면 중간에 언어 설정이 있습니다.

lang: ko-KR

이것을   lang: kr 

로 바꿔주면 hyphen-korean 설치 문제를 회피하는 것 같습니다.

**Comment by letitbk** [comment]
옙! 정말 감사합니다. @rjmcmc 말씀하신대로, 위의 hyphen-korean 문제는 해결을 할 수 있었는데요, 여전히 아래에 나오는 compliation failed error가 나오는데, 혹시 이 문제는 어떻게 해결할 수 있을까요? 
```
ERROR: 
compilation failed- error
Package ltcaption Error: \caption is not available in longtable* environment.

See the ltcaption package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.1585 ...Borgatti, Mehra and others 2009, p 894)}
                                                  \\ 
```

**Comment by rjmcmc** [comment]
이 문제는 제가 경험하지 못해서 확답하기는 어려운데요. 이건 latex에서 ltcaption 패키지를 preamble에 두었을 때, \caption이 longtable* 환경에서 허용되지 않는다고 하네요. 중간에 생기는 .tex 문서를 컴파일하면 아마 같은 오류가 나올텐데 비교해서 수정해야 할 것 같습니다.
