### ISSUE TITLE
Latex 버전 불일치 컴파일 오류

### ISSUE THREAD

**Issue by statkclee** [bit2r/bitPublish#65]
bitPublish 를 맥에서 오랜만에 컴파일하려고 하니... 오류가 다음과 같이 생겼습니다.

```
✘  ~/bitPublish   main ±  latex --version
pdfTeX 3.141592653-2.6-1.40.25 (TeX Live 2023)
kpathsea version 6.3.5
Copyright 2023 Han The Thanh (pdfTeX) et al.
There is NO warranty.  Redistribution of this software is
covered by the terms of both the pdfTeX copyright and
the Lesser GNU General Public License.
For more information about these matters, see the file
named COPYING and the pdfTeX source.
Primary author of pdfTeX: Han The Thanh (pdfTeX) et al.
Compiled with libpng 1.6.39; using libpng 1.6.39
Compiled with zlib 1.2.13; using zlib 1.2.13
Compiled with xpdf version 4.04
```

```
  title: bitPublish를 이용하여 한글 책 조판하기
  

Rendering PDF
running xelatex - 1
  This is XeTeX, Version 3.141592653-2.6-0.999995 (TeX Live 2023) (preloaded format=xelatex)
   restricted \write18 enabled.
  entering extended mode
  
updating tlmgr

updating existing packages
finding package for KoPubWorld돋움체_Pro(-(Bold|Italic|Regular).*)?[.](tfm|afm|mf|otf|ttf)
ERROR: Your TexLive version is not updated enough to connect to the remote repository and download packages. Please update your installation of TexLive or TinyTex.

Underlying message: Local TeX Live (2023) is older than remote repository (2024).
Cross release updates are only supported with
  update-tlmgr-latest(.sh/.exe) --update
See https://tug.org/texlive/upgrade.html for details.


Stack trace:

Underlying message: Local TeX Live (2023) is older than remote repository (2024).
Cross release updates are only supported with
  update-tlmgr-latest(.sh/.exe) --update
See https://tug.org/texlive/upgrade.html for details.

    at findPackages (file:///Users/tidyverse/Applications/quarto/bin/quarto.js:76446:27)
    at eventLoopTick (ext:core/01_core.js:153:7)
    at async findAndInstallPackages (file:///Users/tidyverse/Applications/quarto/bin/quarto.js:77279:30)
    at async initialCompileLatex (file:///Users/tidyverse/Applications/quarto/bin/quarto.js:77171:39)
    at async generatePdf (file:///Users/tidyverse/Applications/quarto/bin/quarto.js:77116:22)
    at async Object.complete (file:///Users/tidyverse/Applications/quarto/bin/quarto.js:77396:27)
    at async file:///Users/tidyverse/Applications/quarto/bin/quarto.js:70763:31
    at async withTimingAsync (file:///Users/tidyverse/Applications/quarto/bin/quarto.js:19479:25)
    at async Object.complete (file:///Users/tidyverse/Applications/quarto/bin/quarto.js:70761:13)
    at async renderSingleFileBook (file:///Users/tidyverse/Applications/quarto/bin/quarto.js:92859:30)
```

**Comment by choonghyunryu** [comment]
@statkclee 

bitPublish 예제 문서의 Troubleshooting Chapter에 해당 솔루션이 기술되어 있습니다.
다음과 같이 조치하시면 됩니다.

매년 4월 TeXlive는 원격저장소를 TeX의 새해 버전으로 업데이트합니다. 이 경우 TeX의 이전 년도 설치본은 원격 저장소에서 패키지를 다운로드/설치할 수 없습니다. 사용자가 TeXlive 또는 TeXlive는 원격저장소를 이용하는 TinyTex을 업데이트 해야 합니다.

TeXlive를 사용한다면, 다음 명령으로 TeXlive를 업데이트하세요.

```
update-tlmgr-latest --update
```

TinyTex을 사용한다면, 다음 명령으로 TinyTex을 업데이트하세요.

```
quarto update tinytex
```
